// Generated by CoffeeScript 1.6.3
(function() {
  var FacebookClient;

  FacebookClient = (function() {
    function FacebookClient(appId) {
      var that;
      this.appId = appId;
      that = this;
      window.fbAsyncInit = function() {
        var sdkParameters;
        sdkParameters = {
          appId: that.appId,
          status: true,
          xfbml: true
        };
        FB.init(sdkParameters);
        return $(document).trigger('FbApiReady');
      };
      this.loadSdk(document, 'script', 'fb-jssdk');
    }

    FacebookClient.prototype.loadSdk = function(d, s, id) {
      var fjs, js;
      fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {
        return;
      }
      js = d.createElement(s);
      js.id = id;
      js.src = '//connect.facebook.net/en_US/all.js';
      return fjs.parentNode.insertBefore(js, fjs);
    };

    FacebookClient.prototype.requestAccess = function() {
      var that;
      that = this;
      return FB.login(function(response) {
        if (response.authResponse) {
          return $(document).trigger('FbAccessGranted');
        } else {
          return $(document).trigger('FbAccessDenied');
        }
      }, {
        scope: 'email'
      });
    };

    FacebookClient.prototype.getInformations = function() {
      return FB.api('/me', function(response) {
        if (!response || response.error) {
          return $(document).trigger('FbUserDataRetrieveFailed', response);
        } else {
          return $(document).trigger('FBDataFetched', response);
        }
      });
    };

    return FacebookClient;

  })();

  window.facebookClient = FacebookClient;

}).call(this);

//# sourceMappingURL=FacebookClient.map
